### PR TITLE
Elements should compare native nodes for equality

### PR DESCRIPTION
**Pull request by ajjahn**

### CODE REVIEW

**Comment by ajjahn** [comment]
I believe travis is lying to us.

**Comment by jgaskins** [comment]
It is. I don't know how to upgrade PhantomJS on Travis CI :-\

**Comment by jgaskins** [comment]
I'm not sure how this might be useful, but two things being equal that have equal state certainly makes sense. :-)

**Comment by ajjahn** [comment]
Cool!

I had to monkey patch this in to artificially create a "clickoff" event for a modal type component.

**Comment by jgaskins** [comment]
That sounds interesting. How'd you make that work?

I actually like hearing about how people do modals. They're useful in nearly every app but I've never found a pattern to implement them that I really like. :-)

**Comment by ajjahn** [comment]
There's a few parts to it. I'm not sure it's the best approach either, it's kind of just the first thing that worked for me. But hey, maybe you can weight in on where it can be improved!

I've got a couple components. First, there is a `Modal::Manager` component responsible for rendering the last modal in the stack of modals to be displayed. This component is usually rendered last in the app's layout.

```ruby
module Modal
  class Manager
    include Clearwater::Component

    def render
      if current_modal
        div({ class: "modal"}, current_modal)
      end
    end

    def current_modal
      Store.state.modals.last
    end
  end
end
```

Then there is the `Modal` component module. Modals have a promise that, when resolved, dismisses itself. 

```ruby
module Modal
  module Component
    def promise
      @promise ||= Promise.new.tap do |p|
        p.always { Store.dispatch(Dismiss.new(self)) }
      end
    end

    def accept(*args)
      promise.resolve(*args)
    end

    def cancel(*args)
      promise.reject(*args)
    end
  end
end
```

Next, we've got some modal related actions:

```ruby
module Modal
  Action = GrandCentral::Action.create
  Present = Action.with_attributes(:modal) do
    def promise
      modal.promise
    end
  end

  Dismiss = Action.with_attributes(:modal) do
    def promise
      @promise ||= Promise.new
    end
  end
end
```
And some reducer logic (I like to split my reducer logic into smaller callable classes):
```ruby
module Modal
  class Reducer
    def self.call(state, action)
      case action
      when Present
        state + [action.modal]
      when Dismiss
        state - [action.modal]
      else
        state
      end
    end
  end
end
```

The `Modal::Present` action forwards it's promise to the modal instance. This allows a modal to be presented like this:

```ruby
class MyModal
  include Clearwater::Component
  include Modal::Component
  
  def render
    [
      button({ onclick: -> accept("Everything's okay!") }, "Okay"),
      button({ onclick: -> cancel("Call it off!") }, "Cancel"),
    ]
  end
end

# elsewhere...

def render
  button({ onclick: method(:present_modal) }, "Launch Modal")
end

def present_modal
  Store.dispatch(Modal::Present.new(MyModal.new))
    .then { |result| puts result } #=> "Everything's okay!"
    .fail { |result| puts result } #=> "Call it off!"
end
```

**Comment by ajjahn** [comment]
For the "click off" event, this works, but I'd love to find a better way to do it. I had to resort to vdom hooks.

I created a `DOMReference` subclass that forward the hook and unhook methods to a delegate object:

```ruby
class VDOMHookDelegate < Clearwater::DOMReference
  attr_reader :delegate, :node

  def initialize(delegate)
    @delegate = delegate
  end

  %i(before_hook after_hook before_unhook).each do |method|
    define_method(method) do |*args|
      delegate.send(method, *args) if delegate.respond_to?(method)
    end
  end

  def wrap node
    @node ||= Bowser::Element.new(node)
  end

  def to_n
    self
  end

  %x{
    Opal.defn(self, 'hook', function(node, name, previous) {
      var self = this;
      #{before_hook(wrap(`node`), `previous`)};
      setTimeout(function(){
        #{after_hook(wrap(`node`), `previous`)};
      }, 0);
    });
    Opal.defn(self, 'unhook', function(node, name, previous) {
      var self = this;
      #{before_unhook(wrap(`node`), `previous`)};
    });
  }
end


```

Then this next component listens for clicks on a parent element; in most cases the html body. Unfortunately, it has to fiddle with creating and cleaning up the event listeners on that element. The `click_off` method compares the `Bowser::Element`s to find out if the click event target is contained in the ClickTrap component. If not, it calls the clickoff callback.

```ruby
class ClickTrap
  include Clearwater::Component

  def initialize(attributes = {}, children = [])
    @parent = attributes.delete(:parent) || Bowser.document.body
    @onclick = attributes.delete(:onclick)
    @onclickoff = attributes.delete(:onclickoff)
    @attributes = attributes.merge({ __ref: ref, onclick: method(:click_on) })
    @children = children
  end

  def ref
    @ref ||= VDOMHookDelegate.new(self)
  end

  def after_hook(element)
    @parent_listener ||= @parent.on(:click, &method(:click_off))
  end

  def before_unhook(element)
    parent.off(:click, &@parent_listener)
  end

  def click_on(event)
    @onclick.call(event) if @onclick
  end

  def click_off(event)
    return if ref.contains(event.target) || ref.node == @parent
    @onclickoff.call(event) if @onclickoff
  end

  def render
    div(@attributes, @children)
  end
end
```

So a modal that wants to dismiss when it is 'clicked off' might do something like this:
```ruby
def render
  ClickTrap.new({ onclickoff: -> { cancel } }, ...)
end
```

Like I said, I'd like to improve this implementation. It works, but it doesn't feel great.

**Comment by jgaskins** [comment]
Interesting. I like your use of vdom hooks there. I've been thinking of adding support for them — I thought `DOMReference` would be enough (and it has been, for most things), but I've implemented my own hook classes twice in the past couple weeks just to get arbitrary behavior when the element was created. I'll open an issue for that.

The way I've done modals with Clearwater is a bit simpler, but I don't know if it's a decent general-purpose solution:

```ruby
# Using a struct to save boilerplate
Modal = Struct.new(:content) do
  include Clearwater::Component

  def render
    # Yeah, I'm one of those people who uses inline styles. ;-)
    div({ style: Style.overlay, onclick: method(:cancel) }, [
      div({ style: Style.content }, content),
    ])
  end

  def cancel
    Store.dispatch CloseModal.new
  end

  module Style
    module_function

    def overlay
      {
        position: :absolute,
        background: 'rgba(0, 0, 0, 0.3)',
        top: 0, bottom: 0,
        left: 0, right: 0,
        text_align: :center,
      }
    end

    def content
      {
        background: :white,
        color: :black,
        display: 'inline-block',
        padding: '1.25em',
        height: '500px',
        width: '300px',
        max_width: '80%',
        margin: '2em auto',
        text_align: :center,
      }
    end
  end
end

ModalAction = GrandCentral::Action.create
OpenModal = ModalAction.with_attributes(:content)
CloseModal = ModalAction.create

module Reducers
  Modal = proc do |state, action|
    case action
    when OpenModal
      ::Modal.new(action.content)
    when CloseModal
      nil
    else
      state
    end
  end
end

class Layout
  include Clearwater::Component

  def render
    div([
      # ...

      # Put the modal as high up the DOM as we can to reduce possibility of being
      # contained within a `position: relative` element.
      Store.state.modal,
    ])
  end
end
```

What I liked about yours was the ability to have multiple modals open. One thing that I do see as a problem with my solution is that if you don't call `event.stop_propagation` on your content's click handlers, the click event bubbles up to the overlay and closes the modal.

**Comment by ajjahn** [comment]
I like your idea of dispatching the content and wrapping it in a modal. That's a nice shortcut if you don't want to create a component for each modal you want to display. 

Yeah, I missed the event propogation code when I was pasting the click trap in here. I made it an option on the click trap.

How are you handling feedback from your modals? I resorted to implementing promises because I haven't been able to come up with a strategy for storing state for anonymous UI components in a store.

**Comment by jgaskins** [comment]
Since modal content is a component that dispatches actions just like others, it dispatches an action that removes the modal. :-)

**Pull request merged**
