### PR TITLE
Add Promise implementation

### PR DESCRIPTION
**Pull request by jgaskins**
Opal provides a [Promise class](https://github.com/opal/opal/blob/master/stdlib/promise.rb) in its standard library, but it isn't quite as powerful as ES6 promises. This PR intends to provide something closer to how promises are intended to work at a lighter weight — just over 1/3 the size of Opal's `Promise` class (120 lines vs 340 lines).

For example:

``` ruby
# Resolving a promise with another promise
p = Promise.new
p.resolve(Bowser::HTTP.fetch(url))

# Chained promises resolving with the value of the previous block
Bowser::HTTP.fetch(url)
  .then { |resp| resp.json }
  .then { |hash| handle hash }

# Resolve/reject when any given promise resolves/rejects
Promise.race(promises)
```

The only thing about this I know of that doesn't comply with the [A+ spec](https://promisesaplus.com) is deferred execution after resolution:

> onFulfilled or onRejected must not be called until the execution context stack contains only platform code.

### CODE REVIEW

**Comment by jgaskins** [comment]
Note that this doesn't wrap JS promises. It's a complete Ruby implementation of them. I think I'd like to try adding `.from_native` and `#to_n` methods to go back and forth between JS promises, though, or at least provide a JS-level `.then` method to make them interoperable.

I haven't tried this at all, but I think it'd be kind cool to make it usable with JS libraries that use native promises.

**Comment by bwl21** [comment]
If this promise implementation is intended as a replacement of Opal's promise class, then #when should be provided or documented as a non backwards compatible change.

t seems that Opal's promise implementation deviates from ES6 since it provides the 'when'.

**Comment by jgaskins** [comment]
> If this promise implementation is intended as a replacement of Opal's promise class

It's not. This project is simply a Ruby port of browser APIs. API compatibility with alternatives built into Opal or `opal-browser` are not part of the goal, especially where they deviate from browser APIs.

The idea is more that you can read API docs on MDN or whatever and intuit most of Bowser's APIs from it. Being closer to JS APIs also reduces the amount of code you need to port from JS to Ruby. I've had great success with these goals.

> seems that Opal's promise implementation deviates from ES6 since it provides the 'when'.

Oh, man, there's a lot more than that. :-)

- A `Promise.all`-compatible method is not provided.
- Instead, they use `Promise.when`, but you must pass each promise as a separate argument, rather than passing an `Enumerable` (`iterable` in JS parlance) object.
- `Promise.race` is not provided at all.
- ES6's `Promise.resolve` is called `Promise.value` in the Opal implementation.
- It didn't allow the same promise to be chained multiple times until [this PR](https://github.com/opal/opal/pull/1263). That was an intentional decision on their part and they made it clear that that PR wouldn't have merged without support for that.
- `Promise#catch` is called `fail`, but they alias it to `rescue` which I actually think is pretty cool since the JS keyword `catch` is `rescue` in Ruby. However, no `catch` alias.

The following are places both implementations deviate but I don't think they're a big deal:
- The constructor doesn't yield `onResolve` and `onReject` functions as positional arguments.
  - Bowser yields the promise object itself to call those methods on. Ruby is more about objects than functions.
  - Opal doesn't allow taking a block in the constructor, but you can use `tap` or procedural-style code to get the same functionality Bowser gives you.
- `then` takes a single callback to invoke on `resolve`, rather than taking multiple callbacks.
  - This is fine because the ES6 spec also allows a `catch` method, which is functionally equivalent to calling `promise.then(null, onReject)` in JS, and I've seen almost no JS code in the wild that passes two functions to `then`. Nearly everyone uses `catch`.

It's up to Opal whether they conform to ES specs, but that's a goal here.

**Comment by zetachang** [comment]
@jgaskins have you checked out https://github.com/lgierth/promise.rb ? Looks like it's implemented in platform agnostic way.

Also, is it possible to use the this implementation as a polyfill of `window.Promise`? This is helpful since native promise is not widely supported so far and we could also run Promises/A+ test suite against it.

**Comment by jgaskins** [comment]
Someone at one of the local meetups told me about promise.rb _right after_ I put this PR together. :-) I've been thinking of trying that, too (I try a lot of experiments as PRs in all of the clearwater-rb repos if I'm not sure which way to go), but I just haven't checked it yet.

> native promise is not widely supported so far

IE is the [only browser](http://caniuse.com/#feat=promises) missing native promise support at this point. All other browsers have had them for a couple years. Unfortunately, complete lack of support from IE does mean we can't assume they're there. Once Microsoft drops support for IE completely, it might not be a bad idea to move to a simple Ruby wrapper around `window.Promise`.

I've got one in #5, but it isn't much smaller and I'm not even sure how well it works, tbh. :-) I've only tested it with my minimal knowledge of `ServiceWorker`.

> is it possible to use the this implementation as a polyfill of `window.Promise`?

I don't think so. For that, I think we'd need an actual JS polyfill. I have thought about using a Ruby wrapper around native promises as mentioned above and just providing a polyfill for IE, but I don't want to bloat the JS payload in every non-IE browser or tell app developers they need to load the polyfill if they want to support IE. The pure-Ruby promise implementation is smaller than polyfill+wrapper, so I'm fine using it until it's no longer needed.

**Comment by jgaskins** [comment]
It came to my attention a couple days ago that ES6 promises don't reject all the way down the chain the way this implementation does. For example:

```ruby
catch_count = 0
then_count = 0
promise
  .then { then_count += 1 }
  .then { raise 'hell' }
  .catch { catch_count += 1 }
  .catch { catch_count += 1 }
  .then { then_count += 1 }
```

In this example, `catch_count` should be 1 (the second shouldn't be called because the failure is already caught) and `then_count` should be 2 (the last `then` _is_ executed because the failure above it is caught), but this PR executes both `catch`es and only the first `then`. I'll update and merge when I get a chance.

**Pull request merged**
