### PR TITLE
Add URL parser

### PR DESCRIPTION
**Pull request by jgaskins**
This is ugly, and I'm sorry.

### CODE REVIEW

**Comment by ajjahn** [comment]
@jgaskins Do you think this could be useful as a tiny opal gem of it's own since opal doesn't implement Ruby's uri library?

**Comment by jgaskins** [comment]
Possibly. I originally intended this to be an easier abstraction for https://github.com/clearwater-rb/clearwater/issues/64 but it's probably more generally useful than that. No matter which way it goes, we might want to either adjust the API to match the [JS `URL` prototype](https://developer.mozilla.org/en-US/docs/Web/API/URL) or Ruby's `URI`. Either one is probably fine.

**Comment by ajjahn** [comment]
I pulled this down and started molding it toward Ruby's URI. https://github.com/ajjahn/opal-uri

I think implementing basic url parsing and possibly adding an implementation of `URI.encode_www_form` and `URI.decode_www_form` would cover most people's needs.

Obviously, matching Ruby's URI means some of the method names change, with the biggest difference being that the `query` method just returns a string and not a query params hash.

**Comment by jgaskins** [comment]
> the biggest difference being that the query method just returns a string and not a query params hash

Yeah, I actually leaned toward JS's `URL` prototype with the hash. With all the things Ruby's `URI` does, the fact that it only gives you query params as a string feels so archaic. :-)

**Comment by jgaskins** [comment]
Closing this for now. @ajjahn released the [`opal-uri` gem](https://rubygems.org/gems/opal-uri) and that functionality [may also get pulled into Opal itself](https://gitter.im/opal/opal?at=58427fcdf666c5a138c3a2a1). May reopen and improve this the future if people want something closer to the JS `URL` prototype.

**Pull request closed without merging**
