### PR TITLE
Add support for data-* attributes

### PR DESCRIPTION
**Pull request by ajjahn**

### CODE REVIEW

**Comment by jgaskins** [comment]
Nice! Your `method_missing` code is really clean. I like it a whole lot more than the [gnarly mess I made](https://github.com/clearwater-rb/bowser/blob/7a706fd0f23d61d9cfc4344582ae0b8e89e26e71/opal/bowser/element.rb#L82-L118) in `Element`.

**Comment by ajjahn** [comment]
Well, to be fair, your gnarly mess is doing a whole lot more than the `method_missing` in this PR.

On a side note: I notice at least 3-4 places where camelization is implemented. Any interest in a `Bowser::Utils` module that DRYs that up?

**Comment by jgaskins** [comment]
> Any interest in a Bowser::Utils module that DRYs that up?

Absolutely. I've been wanting to clean up some of the code in this repo.

**Comment by jgaskins** [comment]
I was about to merge this and I realized that, given the following ways to set these attrs:

- Server-rendered HTML
  - `<div data-item-id="123"></div>`
- Client-rendered using attributes API
  - `div(attributes: { "data-item-id": 123 })`
- Client-rendered via properties API
  - `div(dataset: { item_id: 123 })`

This PR can get the first two, but not the last one.

This is actually one of my biggest pet peeves about front-end development: DOM attributes and properties hardly resemble each other at all. :-) I still think this is a good idea, though, and camelization is probably the way to go because I can't imagine people store a whole lot of data on client-rendered DOM elements. I just wanted to have the conversation to try to make sure I'm not simply misled by my own experiences.

**Comment by ajjahn** [comment]
Yeah, the attribute vs property inconsistency is a pain. I don't particularly understand why [property name conversion](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) is really necessary.

I agree that the third example is probably rare. If we really wanted, we could allow the subscript methods to skip camelization and only camelize through `method_missing`. I'm not sure that's any better because it will allow the attribute vs property inconsistency to leak further into your application.

**Comment by ajjahn** [comment]
Or, maybe add `get` and `set` [DOMStringMap property methods](https://developer.mozilla.org/en-US/docs/Web/API/DOMStringMap)?

**Comment by jgaskins** [comment]
I was just thinking about this and I wondered if maybe we should just provide `[]` and `[]=` as a method to get and set attributes? Then we'd just be returning strings for everything and we don't have to worry about conversion at all.

**Comment by ajjahn** [comment]
Do you mean any attribute on the `Element` or just the data attributes?

**Comment by jgaskins** [comment]
All attributes. Just mapping `[]` to `getAttribute` and `[]=` to `setAttribute`. Then we could say `element['data-item-id']` and completely ignore all of the capitalization-conversion frustration.

**Comment by jgaskins** [comment]
Merged in #23 to add support for attributes via `[]` operator, so I'm gonna close this since that gives us access to `data-*` attributes. Thanks for submitting it, though! :-) Sorry I neglected it so long.

**Pull request closed without merging**
